name: Bug Report
description: File a bug report
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Explain in detail what exactly happened
    validations:
      required: true
  - type: textarea
    id: reproducible-code
    attributes:
      label: What the code you used and failed
      description: Write the code you used, to help us reproduce the bug
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of the framework are you using?
      placeholder: ex. 0.0.1
    validations:
      required: false
  - type: dropdown
    id: python
    attributes:
      label: What python version do you use?
      multiple: true
      options:
        - 3.7
        - 3.8
        - 3.9
        - 3.9
  - type: dropdown
    id: os-version
    attributes:
      label: What operating system are you running?
      multiple: true
      options:
        - Linux
        - Windows
        - OSX
        - Other
    validations:
      required: true