batch_size: 2            # Kích thước mỗi batch huấn luyện  
num_epochs: 10            # Số lượng epoch huấn luyện  
learning_rate: 0.0001      # Tốc độ học (learning rate)  
sample_rate: 16000        # Tần số lấy mẫu audio (Hz)  

vocab_folder: "C:\\paper\\T-T\\vocab_folder" # Đường dẫn đến file vocab_path, w2i, i2w
vocab_path: "C:\\paper\\T-T\\vocab_folder\\vocab.txt"     # Đường dẫn tới file vocabulary (sẽ tạo nếu chưa có)

# Đường dẫn file JSON chứa danh sách dữ liệu train
train_json: "C:\\paper\\raw_data\\Vietnamese-Speech-to-Text-datasets\\Common-Voice\\newdata\\processed_train.json"    
# Đường dẫn file JSON chứa danh sách dữ liệu dev   
dev_json: "C:\\paper\\raw_data\\Vietnamese-Speech-to-Text-datasets\\Common-Voice\\newdata\\processed_dev.json" 
# Đường dẫn file JSON chứa danh sách dữ liệu test        
test_json: "C:\\paper\\raw_data\\Vietnamese-Speech-to-Text-datasets\\Common-Voice\\newdata\\processed_test.json"
# Thư mục chứa các file âm thanh (.wav/.mp3)       
wav_folder: "C:\\paper\\raw_data\\Vietnamese-Speech-to-Text-datasets\\Common-Voice\\voices"          
